version: '2'
services:
  master:
      image: vitaled/spark:latest
      hostname: master
      expose:
        - 7001
        - 7002
        - 7003
        - 7004
        - 7005
        - 7006
        - 7077
        - 6066
      ports:
        - "4040:4040"
        - "6066:6066"
        - "7077:7077"
        - "8080:8080"
      environment:
        - MASTER=spark://master:7077
        - SPARK_CONF_DIR=/conf/master
      command: spark-class org.apache.spark.deploy.master.Master -h master
  worker:
      image: vitaled/spark:latest
      hostname: worker
      environment:
        - MASTER=spark://master:7077
        - SPARK_CONF_DIR=/conf/worker
        - SPARK_WORKER_CORES=2
        - SPARK_WORKER_MEMORY=1g
        - SPARK_WORKER_PORT=8881
        - SPARK_WORKER_WEBUI_PORT=8081
      volumes_from:
        - data_vol
      command: spark-class org.apache.spark.deploy.worker.Worker spark://master:7077
      links:
        - master
      expose:
        - 7012
        - 7013
        - 7014
        - 7015
        - 7016
        - 8881
        - 8081
  data_vol:
     image: busybox
     volumes:
       - ./data:/data
       - ./conf:/conf
